export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ASYNC = 'ASYNC'
export const CHANGE_THEME = 'CHANGE_THEME'
export const DISABLE_BTN = 'DISABLE_BTN'
export const ENABLE_BTN = 'ENABLE_BTN'
